<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>05_为什么要用Promise</title>
</head>
<body>

<script>
    /* 
      1. 指定回调函数的方式更加灵活: 
        旧的: 必须在启动异步任务前指定
        promise: 启动异步任务 => 返回promise对象 => 给promise对象绑定回调函数(甚至可以在异步任务结束后指定)

      2. 支持链式调用, 可以解决回调地狱问题
        什么是回调地狱? 回调函数嵌套调用, 外部回调函数异步执行的结果是嵌套的回调函数执行的条件
        回调地狱的缺点?  不便于阅读 / 不便于异常处理
        解决方案? promise链式调用
        终极解决方案? async/await
      */

    // 成功的回调函数
    function successCalBack(result) {
        console.log("声音文件创建成功: " + result);
    }

    // 失败的回调函数
    function failureCalBack(eror) {
        console.log("声音文件创建失败: " + eror);
    }

    /* 1. 使用纯回调函数 */
    createAudioFileAsync(audioSettings, successCalBack, failureCalBack)
    /* 1.2 使用 Promise */
    const promise = createAudioFileAsync(audioSettings);
    setTimeout(() => {
        promise.then(successCalBack, failureCalBack);
    }, 30);
    /*
    2.1 回调地狱
    */
    doSmething(function (result) {
        doSmethingElse(result, function (ewResult) {
            doThirdThing(newResult, function (finalResult) {
                console.log('Gothe final result: ' + finalResult)
            }, failureCalBack)
        }, failureCalBack)
    }, failureCalBack)
    /*
    2. 使用 promise 的链式调用解决回调地狱
    */
    doSmething().then(function (result) {
        return doSmethingElse(result)
    })
        .then(function (ewResult) {
            return doThirdThing(newResult)
        }).then(function (finalResult) {
        console.log('Gothe final result: ' + finalResult)
    })
        .catch(failureCalBack)

    /*
    2.3 async/awit: 回调地狱的终极解决方案
    */
    async function request() {
        try {
            const result = awit
            doSmething()
            const newResult = awit
            doSmethingElse(result)
            const finalResult = awit
            doThirdThing(newResult)
            console.log('Gothe final result: ' + finalResult)
        } catch (eror) {
            failureCalBack(eror)
        }
    }


</script>
</body>
</html>